types_translations = {
    'airport': 'Airport',
    'atm': 'ATM',
    'bar': 'Bar',
    'bank_intl': 'Bank',
    'bus': 'Bus',
    'cafe': 'Café',
    'camping': 'Camping',
    'cemetery': 'Cemetery',
    'civic_bldg': 'Civic building',
    'ferry': 'Ferry',
    'gas': 'Gas',
    'generic': 'Generic',
    'golf': 'Golf',
    'hospital_H': 'Hospital H',
    'library': 'Library',
    'lodging': 'Lodging',
    'monument': 'Monument',
    'movie': 'Movie',
    'museum': 'Museum',
    'parking': 'Parking',
    'police': 'Police',
    'postoffice': 'Post office',
    'restaurant': 'Restaurant',
    'school': 'School',
    'shoppingbag': 'Shopping bag',
    'shoppingcart': 'Shopping cart',
    'train': 'Train',
    'tram': 'Tram',
    'tree': 'Park',
    'worship_buddhist': 'Worship Buddhist',
    'worship_christian': 'Worship Christian',
    'worship_hindu': 'Worship Hindu',
    'worship_islam': 'Worship Islam',
    'worship_jewish': 'Worship Jewish',
    'worship_sikh': 'Worship Sikh',
    'worship_jain': 'Worship Jain'
}
